<link href='https://fonts.googleapis.com/css?family=Oswald:700' rel='stylesheet' type='text/css'>
<style>
    .top-main{
        position: relative;
    }
    .top-main::after {
        content: "";
        width: 0;
        height: 0;
        position: absolute;
        border: 20px solid transparent;
        border-top: 28px solid white;
        bottom: -48px;
        right: 49%;
    }
    .top-main h1{
        margin: 0;
        padding: 45px;
        font-size: 45px;
        font-family: "Oswald";
        color: rgb(68, 68, 68);
        font-weight: bold;
        text-transform: uppercase;
        line-height: 1.2;
    }
    .col1-layout{
        background-color: #e9e9e9;
        box-shadow: 0 10px  0 #b8b6b0;
    }
    #contactForm input, #contactForm textarea {
        border-radius: 0;
    }

    .submit {
        padding-top: 77px;
   }
    .submit button.button span{
        background-color: #de3626;
    }
    .contacts-index-index h2.legend{
        font-weight: bold;
    }
    .form-list textarea{
        height:7em;
    }
    #contactForm > .legend{
        color: black;
    }
    .contact-info  > h2{
        font-size: 31px !important;
        font-family: "Oswald";
        color: rgb(68, 68, 68);
        font-weight: bold;
        text-transform: uppercase;
        line-height: 1.2;
    }
    .col-main{
        padding-bottom: 80px;
        padding-top: 80px;
    }
    .main-container{
        padding: 0;
    }
    .contact-detail b{
        color: black;
    }
    .line-block{
        height: 320px;
    }
    .line{
        width: 2px;
        background-color: rgb(197, 197, 197);
        height: 100%;
        margin-top: 8px;
        margin-left: 18px;
    }


    @media (min-width: 425px) and (max-width: 767px){
        .legend{
            text-align: center;
        }
    }
    @media (max-width: 768px) {
        .submit{
            padding-top: 20px;
            margin-left: 25% !important;
        }
        .submit button{
            width:100%;
        }
        .line-block{
            display: none;
        }
    }
    .Divider {

        position: absolute;
        left: 990px;
        top: 409px;

        height: 301px;
        z-index: 31;
    }

</style>
<?php
$store = Mage::app()->getStore();
$code = $store->getCode();

$_infoblock = Mage::getStoreConfig('porto_settings/contacts/infoblock', $code);
?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<div class="row">
    <div class="col-sm-3 contact-info">
        <h2 class="legend"><?php echo Mage::helper('contacts')->__('') ?>
            <b><?php echo Mage::helper('contacts')->__('BUTCHER DIRECT') ?></b></h2>
        <?php
        echo $_infoblock;
        ?>
    </div>
    <div class="col-sm-1 line-block">
        <div class="line"></div>
    </div>
    <div class="col-sm-8 " id="form-contact">
        <form action="<?php echo $this->getFormAction(); ?>" id="contactForm" method="post" >
            <h2 class="legend"><?php echo Mage::helper('contacts')->__('Leave') ?>
                <b><?php echo Mage::helper('contacts')->__('a Massage') ?></b></h2>

            <div class="row">
                <ul class="form-list col-sm-6">
                    <li>
                        <label for="name"
                               class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Full Name') ?>
                        </label>

                        <div class="input-box">
                            <input name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Name') ?>"
                                   value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?>"
                                   class="input-text required-entry" type="text"/>
                        </div>
                    </li>
                    <li>
                        <label for="massage-type"
                               class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Massage Type') ?>
                        </label>

                        <div class="input-box">
                            <select name="massage-type" id="massage-type" class="required-entry"
                                    style="border-radius: 0">
                                <option value="1">Select</option>
                                <option value="2">Type 2</option>
                                <option value="3">Type 3</option>
                            </select>
                            <!--                    <input name="massage-type" id="massage-type" title="-->
                            <?php //echo Mage::helper('contacts')->__('Name') ?><!--" value="-->
                            <?php //echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?><!--" class="input-text required-entry" type="text" />-->
                        </div>
                    </li>
                    <!--            <li>-->
                    <!--                <label for="telephone">-->
                    <?php //echo Mage::helper('contacts')->__('Telephone') ?><!--</label>-->
                    <!--                <div class="input-box">-->
                    <!--                    <input name="telephone" id="telephone" title="-->
                    <?php //echo Mage::helper('contacts')->__('Telephone') ?><!--" value="" class="input-text" type="text" />-->
                    <!--                </div>-->
                    <!--            </li>-->
                </ul>
                <ul class="form-list col-sm-6">
                    <li>
                        <label for="email"
                               class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Email Address') ?>
                        </label>

                        <div class="input-box">
                            <input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>"
                                   value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()) ?>"
                                   class="input-text required-entry validate-email" type="text"/>
                        </div>
                    </li>
                </ul>
                <div class="row">
                    <ul class="form-list col-sm-12">
                        <li class="col-sm-10">
                            <label for="comment"
                                   class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Your Massage') ?>
                            </label>

                            <div class="input-box input-textarea">
                                <textarea name="comment" id="comment"
                                          title="<?php echo Mage::helper('contacts')->__('Comment') ?>"
                                          class="required-entry input-text" cols="5" rows="2"
                                          placeholder="<?php echo Mage::helper('contacts')->__('Comment') ?>"></textarea>
                            </div>
                        </li>
                        <li class="col-xs-6 col-xs-offset-3 col-sm-2 submit ">
                            <input type="text" name="hideit" id="hideit" value="" style="display:none !important;"/>
                            <button type="submit" title="<?php echo Mage::helper('contacts')->__('Submit') ?>"
                                    class="button">
                                <span><span><?php echo Mage::helper('contacts')->__('SUBMIT') ?></span></span></button>
                        </li>
                    </ul>
                </div>

            </div>
        </form>
        <script type="text/javascript">
            //<![CDATA[
            var contactForm = new VarienForm('contactForm', true);
            //]]>
        </script>
    </div>

</div>


