<?php
 /**
 * BssCommerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * BssCommerce does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * BssCommerce does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   BSS
 * @package    BSS_Deliverydate
 * @author     Extensions Team
 * @copyright  Copyright (c) 2014-2105 BssCommerce Co. (http://bsscommerce.com)
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php /** @var $this Mage_Sales_Block_Order_Info */ ?>
<?php $_order = $this->getOrder() ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('Order #%s - %s', $_order->getRealOrderId(), $_order->getStatusLabel()) ?></h1>
    <?php echo $this->getChildHtml('buttons') ?>
</div>
<?php echo $this->getStatusHistoryRssUrl($_order) ?>
<dl class="order-info">
    <dt><?php echo $this->__('About This Order:') ?></dt>
    <dd>
        <?php $_links = $this->getLinks(); ?>
        <ul id="order-info-tabs">
            <?php foreach ($_links as $_link): ?>
                <?php if($_link->getUrl()): ?>
                    <li><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
                    <?php else: ?>
                    <li class="current"><?php echo $_link->getLabel() ?></li>
                    <?php endif; ?>
                <?php endforeach; ?>
        </ul>
        <script type="text/javascript">decorateGeneric($('order-info-tabs').select('LI'),['first','last']);</script>
    </dd>
</dl>
<p class="order-date"><?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?></p>
<?php if (!$_order->getIsVirtual()): ?>
    <div class="col2-set order-info-box">
        <div class="col-1">
            <div class="box">
                <div class="box-title">
                    <h2><?php echo $this->__('Shipping Address') ?></h2>
                </div>
                <div class="box-content">
                    <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
                </div>
            </div>
        </div>
        <div class="col-2">
            <div class="box">
                <div class="box-title">
                    <h2><?php echo $this->__('Shipping Method') ?></h2>
                </div>
                <div class="box-content">
                    <?php 
                        if ($_order->getShippingDescription()): ?>
                        <?php echo $this->escapeHtml($_order->getShippingDescription()); ?>
                        <br/>
                        <?php 
                  $date_format = Mage::getStoreConfig('deliverydate/deliverydate_general/deliverydate_format');
                    $time_format = Mage::getStoreConfig('deliverydate/deliverydate_general/deliverytime_format');
                    if ($date_format=='')
                        $date_format='d/M/Y';
                    //if($time_format=='')
                    //    $date_format.=" ,g:i a";
                    //else
                        //$date_format.=" ".$time_format;
                    if ($_order->getShippingArrivalDate()!=''&&$_order->getShippingArrivalTimeslot()!='')
                        echo "<strong>Shipping Arrival Date: </strong>".$currentDate = date ($date_format,strtotime($_order->getShippingArrivalDate()))." in ".$_order->getShippingArrivalTimeslot();
					else if ($_order->getShippingArrivalDate()!=''&&$_order->getShippingArrivalTimeslot()=='')
					   echo "<strong>Shipping Arrival Date: </strong>".$currentDate = date ($date_format,strtotime($_order->getShippingArrivalDate()));
					else if ($_order->getShippingArrivalDate()==''&&$_order->getShippingArrivalTimeslot()!='')
					   echo "<strong>Shipping Arrival Timeslot: </strong>".$_order->getShippingArrivalTimeslot();
					else
                       echo "<strong>Shipping Arrival Date: </strong> N/A".$_order->getShippingArrivalDate();
                    if ($_order->getShippingArrivalComments()!='')
                        echo "<br/><strong>Shipping Arrival Comment: </strong>".$_order->getShippingArrivalComments();
                 ?>
                    <?php else: ?>
                        <p><?php echo $this->helper('sales')->__('No shipping information available'); ?></p>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
    <?php endif; ?>
<div class="col2-set order-info-box">
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('Billing Address') ?></h2>
            </div>
            <div class="box-content">
                <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="box box-payment">
            <div class="box-title">
                <h2><?php echo $this->__('Payment Method') ?></h2>
            </div>
            <div class="box-content">
                <?php echo $this->getPaymentInfoHtml() ?>
            </div>
        </div>
    </div>
</div>
