<?php
$_category = Mage::getSingleton('catalog/layer')->getCurrentCategory();
$store = Mage::app()->getStore();
$code  = $store->getCode();
$_helper    = $this->helper('catalog/output');

$categories = $_category->getCollection()
        ->addAttributeToSelect(array('name', 'thumbnail'))
        ->addAttributeToFilter('is_active', 1)
        ->addIdFilter($_category->getChildren())
?>
<div>
	<ul class="subcategories">
	    <?php foreach ($categories as $sub_category): ?>
        <li>
            <div class="sub-img">
            	<a href="<?php echo $sub_category->getUrl() ?>"><img src="<?php echo Mage::getBaseUrl('media') . 'catalog' . DS . 'category' . DS . $sub_category->getThumbnail() ?>" alt="<?php echo $this->htmlEscape($sub_category->getName()) ?>" class="img-responsive" />
            </div>
            <div class="sub-name">
            	<span><?php echo $sub_category->getName() ?></span></a>
            	<span><input type="button" name="shop" value="SHOP >" class="shop"></span>
            </div>
        </li>
	    <?php endforeach; ?>
	</ul>
</div>


<?php if($_description=$_category->getDescription()): ?>
    <div class="category-description std">
        <?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
    </div>
<?php endif; ?>
