<?php

$store = Mage::app()->getStore();
$code = $store->getCode();

$_infoblock = Mage::getStoreConfig('porto_settings/contacts/infoblock', $code);
?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="row butcher">
    <div class="col-sm-3 contact-info">
        <h2 class="legend"><?php echo Mage::helper('contacts')->__('') ?>
            <b><?php echo Mage::helper('contacts')->__('BUTCHER DIRECT') ?></b></h2>
        <?php
        echo $_infoblock;
        ?>
    </div>
    <div class="col-sm-1 line-block">
        <div class="line"></div>
    </div>
    <div class="col-sm-8 " id="form-contact">
        <form action="<?php echo $this->getFormAction(); ?>" id="contactForm" method="post" >
            <h2 class="legend"><?php echo Mage::helper('contacts')->__('Leave') ?>
                <b><?php echo Mage::helper('contacts')->__('a Message') ?></b></h2>

            <div class="row">
                <ul class="form-list col-sm-6">
                    <li>
                        <label for="name"
                               class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Full Name') ?>
                        </label>

                        <div class="input-box">
                            <input name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Name') ?>"
                                   value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?>"
                                   class="input-text required-entry" type="text"/>
                        </div>
                    </li>
                    <li>
                        <label for="message-type"
                               class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Message Type') ?>
                        </label>

                        <div class="input-box">
                            <select name="message-type" id="message-type" class="required-entry"
                                    style="border-radius: 0">
                                <option value="1">Select</option>
                                <option value="2">Type 2</option>
                                <option value="3">Type 3</option>
                            </select>
                            <!--                    <input name="massage-type" id="massage-type" title="-->
                            <?php //echo Mage::helper('contacts')->__('Name') ?><!--" value="-->
                            <?php //echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?><!--" class="input-text required-entry" type="text" />-->
                        </div>
                    </li>
                    <!--            <li>-->
                    <!--                <label for="telephone">-->
                    <?php //echo Mage::helper('contacts')->__('Telephone') ?><!--</label>-->
                    <!--                <div class="input-box">-->
                    <!--                    <input name="telephone" id="telephone" title="-->
                    <?php //echo Mage::helper('contacts')->__('Telephone') ?><!--" value="" class="input-text" type="text" />-->
                    <!--                </div>-->
                    <!--            </li>-->
                </ul>
                <ul class="form-list col-sm-6">
                    <li>
                        <label for="email"
                               class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Email Address') ?>
                        </label>

                        <div class="input-box">
                            <input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>"
                                   value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()) ?>"
                                   class="input-text required-entry validate-email" type="text"/>
                        </div>
                    </li>
                    <li>
                        <label for="capcha"></label>
                        <div class="input-box">
                            <div class="g-recaptcha" data-sitekey="<?php echo $site_key?>"></div>
                        </div>
                    </li>
                </ul>
                <div class="row">
                    <ul class="form-list col-sm-12">
                        <li class="col-sm-9">
                            <label for="comment"
                                   class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Your Message') ?>
                            </label>

                            <div class="input-box input-textarea">
                                <textarea name="comment" id="comment"
                                          title="<?php echo Mage::helper('contacts')->__('Comment') ?>"
                                          class="required-entry input-text" cols="5" rows="2"
                                          placeholder="<?php echo Mage::helper('contacts')->__('Comment') ?>"></textarea>
                            </div>
                        </li>
                        <li class="col-xs-6 col-xs-offset-3 col-sm-3 submit ">
                            <input type="text" name="hideit" id="hideit" value="" style="display:none !important;"/>
                            <button type="submit" title="<?php echo Mage::helper('contacts')->__('Submit') ?>"
                                    class="button">
                                <span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
                        </li>
                    </ul>
                </div>

            </div>
        </form>
        <script type="text/javascript">
            //<![CDATA[
            var contactForm = new VarienForm('contactForm', true);
            //]]>
        </script>
    </div>

</div>


