/**
 * WARNING: Do not change this file. Your changes will be lost.
 * <?php echo date("Y-m-d H:i:s"); ?>
 */

<?php
$helper = Mage::helper('porto');
$d = $helper->getCfgSectionSettings(Mage::registry('cssgen_store'));

if($d['general']['boxed'] == "boxed"){
?>
body.boxed{
<?php
    if(isset($d['general']['out_of_box_color']) && $d['general']['out_of_box_color']){
?>
    background-color:<?php echo $d['general']['out_of_box_color']; ?>;
<?php
    }
    if(isset($d['general']['out_of_box_image']) && $d['general']['out_of_box_image']){
?>
    background-image:url(<?php echo str_replace("http://","//",str_replace("https://","//",Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."porto/page/".$d['general']['out_of_box_image']));?>);
<?php
    } else if(isset($d['general']['out_of_box_color']) && $d['general']['out_of_box_color']) {
?>
    background-image:none;
<?php

    }
?>
}
<?php
}
if($d['general']['border_radius'] == 1) {
?>
    input, select, textarea, button,
    input.input-text,
    .btn, button.button span,
    .sorter .view-mode i, .sorter .view-mode strong i, .sorter .view-mode a:hover i,
    .pager li>a, .pager li > span, .pager .pages li,
    .product-label span,
    a.quickview-icon, a.addtocart, a.comparelink, a.addtowishlist,
    .product-view .product-img-box li.etalage_thumb, .product-view .product-img-box li.etalage_small_thumbs li,
    .qty-changer > a, .add-to-cart button.button span,
    .product-view .product-shop .add-to-links a,
    .sharing-tool-area .addthis_32x32_style .at300bs,
    .product-tabs>ul li, .product-tabs .tab-content,
    .form-list input.input-text, .form-list textarea, .form-list select,
    .block.block-related .product .product-image img,
    .cart .cart-table-wrap, .cart .discount h2, .cart .shipping h2, .cart .cart-collaterals h2,
    .cart .discount h2 + *, .cart .shipping h2 + *, .cart .cart-collaterals h2 + *,
    .cart .discount h2:before, .cart .shipping h2:before,
    .featured-box, .featured-box .box-content, .featured-box .block-flickr-photos a.flickr-image,
    .contacts-index-index .col-main .contact-info i,
    .dashboard .welcome-msg,
    .box .box-title, .box .box-content, .address-list li.item, .form-wrap, #form-validate,
    .postBanner, .postWrapper .post-date .day, .postWrapper .post-date .month, .postBanner img, .block.block-blog-recent ul li div.post-image,
    .commentWrapper i.icon-user, .commentWrapper .comment-area,
    .fancybox-opened .fancybox-skin,
    a.single-image,
    .recent-posts .item .post-image, .recent-posts .item .post-image img,
    .menu.side-menu>li.menu-item-has-children .nav-sublist-dropdown .container ul .menu-item-has-children .nav-sublist,.form-wrap,#form-validate,#login-form,a.at300b .at4-icon, a.at300m .at4-icon,
    .prev-next-products .product-nav .product-pop
    {border-radius:0}

    .header .form-search #search,
    .header .form-search,
    .header-container .selectbox .dropdown,
    .header-container .links,
    .menu-wrapper,
    ul.menu>li,
    .menu>li .nav-sublist-dropdown,
    .topCartContent,
    .block,
    .block .block-title,
    .block .block-title:before,
    .block .block-content,
    .block-layered-nav dt,
    .block-layered-nav dt:before,
    .block-layered-nav dd,
    .block-layered-nav #narrow-by-list .layered-navigation-swatch,
    .product-image-area, .item .product-image,
    .product-swatches-container li a,
    #success-message-container,
    #after-loading-success-message,
    .opc-wrapper-opc .login-trigger, .review-menu-block a.review-total,
    .opc-wrapper-opc #opc-review-block, .md-content,
    .tooltip-popup,
    .category-boxed-banner .owl-item .item,
    blockquote, .img-thumbnail
    {border-radius:0!important}

    .product-image-area{padding:0;border:0}
    .footer-middle .block.block-subscribe .input-box input.input-text{border:1px solid #ccc;background-color:transparent;border-radius:4px;height:34px}
    .footer-middle .block.block-subscribe .input-box button{border-left:1px solid #ccc}
    .footer-middle .block.block-subscribe .input-box button span{background-color:transparent;color:#777;height:34px;line-height:34px}
<?php
}
if($d['general']['layout'] == "full_width"){
?>
    .catalog-category-view .breadcrumbs > .container, .catalog-product-view .breadcrumbs > .container, .catalog-category-view .main-container > .container, .catalog-product-view .main-container > .container { width: 100%; }

    @media (min-width:1280px){
        .catalog-category-view .breadcrumbs > .container, .catalog-product-view .breadcrumbs > .container, .catalog-category-view .main-container > .container, .catalog-product-view .main-container > .container { padding: 0 20px }
        .catalog-category-view  .col2-left-layout .col-main { width: 80%; }
        .catalog-category-view  .col2-left-layout .col-left { width: 20%; }
        .catalog-category-view  .col2-right-layout .col-main { width: 80%; }
        .catalog-category-view  .col2-right-layout .col-right { width: 20%; }
        .catalog-category-view  .col3-layout .col-wrapper { width: 80%; }
        .catalog-category-view  .col3-layout .col-main { width: 75%; }
        .catalog-category-view  .col3-layout .col-left { width: 25%; }
        .catalog-category-view  .col3-layout .col-right { width: 20%; }
        .catalog-product-view  .col2-left-layout .col-main { width: 80%; }
        .catalog-product-view  .col2-left-layout .col-left { width: 20%; }
        .catalog-product-view  .col2-right-layout .col-main { width: 80%; }
        .catalog-product-view  .col2-right-layout .col-right { width: 20%; }
        .catalog-product-view  .col3-layout .col-wrapper { width: 80%; }
        .catalog-product-view  .col3-layout .col-main { width: 75%; }
        .catalog-product-view  .col3-layout .col-left { width: 25%; }
        .catalog-product-view  .col3-layout .col-right { width: 20%; }
    }
<?php
}
if($d['header']['sticky_header'] && $d['header']['sticky_header_mobile']){
?>
	@media (max-width:1279px){
		.header-container.sticky-header.type11{position:fixed;left:0;top:0;width:100%;z-index:50;box-shadow:0 0 3px rgba(0,0,0,.3);transition:all 0.3s;background-color:#555}
	}
    @media (max-width:991px){
		.header-container.sticky-header,.header-container.sticky-header.type12{position:fixed;left:0;top:0;width:100%;z-index:50;box-shadow:0 0 3px rgba(0,0,0,.3);transition:all 0.3s;bottom:auto}

		.header-container.sticky-header.type2 .top-links-container{display:none}
		.header-container.sticky-header.type3 .top-links-container{display:none}
		.header-container.sticky-header.type4 .top-links-container{display:none}
		.header-container.sticky-header.type6 .top-links-container{display:none}
		.header-container.sticky-header.type6 .header-wrapper{display:none}
		.header-container.sticky-header.type9 .top-links-container{display:none}
		.header-container.sticky-header.type10{position:relative}
		.header-container.sticky-header.type10 .menu-wrapper>.custom-menu-block{display:none}
		body.side-header .top-container > .breadcrumbs.fixed-position{position:relative}
		.header-container.sticky-header.type12 .switcher-area{display:none}
		.header-container.sticky-header.type12 .header>.logo{margin:0}
		.header-container.sticky-header.type12 .header>.logo img{height:35px}
		.header-container.sticky-header.type12 .mobile-group{margin-top:4px}
	}
	@media (max-width:768px){
		.header-container.sticky-header.type11 .header-right-area>div{display:none}
		.header-container.sticky-header.type11 .header-right-area>div:first-child{display:block}
	}
    @media (max-width:480px){
		.header-container.sticky-header.type1 .header>.logo img{height:35px}
		.header-container.sticky-header.type1 .header-right-area>div{display:none}
		.header-container.sticky-header.type1 .header-right-area>div:first-child{display:block;margin:20px 0}

		.header-container.sticky-header.type2 .header{padding:5px 0}
		.header-container.sticky-header.type2 .header>.logo img{height:35px;margin:7.5px 0}

		.header-container.sticky-header.type3 .header>.logo{margin-top:7.5px;margin-bottom:7.5px}
		.header-container.sticky-header.type3 .cart-area, .header-container.sticky-header.type3 .search-area, .header-container.type3.sticky-header .menu-icon{margin-top:5px;margin-bottom:5px}
		.header-container.sticky-header.type3 .header>.logo img{height:35px}

		.header-container.sticky-header.type4 .header{padding:5px 0}
		.header-container.sticky-header.type4 .header>.logo img{height:35px;margin:7.5px 0}

		.header-container.sticky-header.type6 .header{padding:5px 0}
		.header-container.sticky-header.type6 .header>.logo img{height:35px;margin:7.5px 0}

		.header-container.sticky-header.type9 .header>.logo{margin-top:7.5px;margin-bottom:7.5px}
		.header-container.sticky-header.type9 .search-area{margin-top:5px;margin-bottom:5px}
		.header-container.sticky-header.type9 .header>.logo img{height:35px}

		.header-container.sticky-header.type11 .header>.logo img{height:35px}
	}
<?php
}
echo $d['custom_settings']['custom_style'];
echo $d['custom_settings']['custom_style_2'];
?>