<?php $menuHelper = Mage::helper('megamenu'); ?>
<?php $menuData = $menuHelper->getMenuData(); extract($menuData); ?>
<style>
    .fixed-header ul.menu >li >a, .main-nav ul.menu >li >a{
        font-size: 18px;
    }
</style>
<div class="header-wrapper">
<div class="main-nav">
    <div class="">
        <div class="menu-wrapper">
            <div class="menu-all-pages-container">
                <ul class="menu container">
                    <?php echo $menuHelper->getMenuContent(); ?>
                </ul>
            </div>
        </div>
    </div>
</div>

</div>

<script type="text/javascript">
    jQuery(document).ready(function(){

    });
//<![CDATA[
var SW_MENU_POPUP_WIDTH = <?php echo $_popupWidth; ?>;
//]]>
</script>