
<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
    
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_showcartbutton = Mage::getStoreConfig('porto_settings/category_grid/show_addtocart', $code);
    $_showcartbutton = Mage::getStoreConfig('porto_settings/category_grid/show_addtolinks', $code);
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" class="img-responsive" />';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>
<div class="category-beef">
	<div class="category-image">
		<div class="category-name">
			<?php echo $this->getCurrentCategory()->getName() ?>
		</div>
		<?php echo $_imgHtml?>
		<div class="container shop-our">
			<p class="shop-text">Shop Our Entire Beef Range</p>
			<input type="button" name="shop-all" class="shop-all" value="SHOP ALL >">
		</div>

	</div>
</div>